# Generated by Django 4.2.10 on 2024-02-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_first_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(blank=True, max_length=255, null=True)),
                ('back', models.CharField(blank=True, max_length=255, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='deck.deck')),
            ],
        ),
    ]
